version: '3'

services:
  ### ElasticSearch ########################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - cluster.name=laravel-listing-cluster
      - node.name=laravel-listing-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
